#!/bin/bash

######################################################
#   Compiles trigram.cpp into the excutable language  #
######################################################

set -e    # halt on first error

link=all  # link all binaries by default
linked=no # track whether we linked

case $1 in  
  -nolink) link=none ; shift ;;  # don't link
esac

# use 'clang++' as the compiler
CPP=clang++

# adds the apropriate flags to compile the file
FLAGS="-g -O -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -pedantic"

# clear out old object files
rm -f *.o

# compile
case $link in
  all) $CPP $FLAGS -o language main.cpp trigram.cpp
                  linked=yes ;;
  none) $CPP $FLAGS -c trigram.cpp ;;
esac
